### PR TITLE
[web-dashboards] Support top projects in dashboards

### PR DESCRIPTION
**Pull request by valeriocos**
This PR addresses the issue https://github.com/crossminer/scava/issues/135. It allows to include meta project information within the enriched items. Meta information is declared in the project description (at the very end) and identified by the marker --meta. Scava2es takes what is after --meta and convert it to a JSON. Currently meta information includes a list of top-projects. If no --meta is given or scava2es fails to parse the JSON, the default top project is set to `main`.

Sentiment, factoids and scava dashboards have been updated accordingly (see image below).

An example of project description including meta information is the following:
```
Send Sir Perceval on a quest to retrieve and gather data from software repositories.
--meta
{
   "top_projects": ["chaoss"] 
}
```

Captura de pantalla de 2019-04-22 17-29-11

### CODE REVIEW

**Comment by valeriocos** [comment]
please @davidediruscio @borisbaldassari @mhow2 have a look when possible, thanks!

**Comment by dlumbrer** [comment]
LGTM @valeriocos :+1:

**Comment by davidediruscio** [comment]
In my opinion, it's a good workaround also in light of the fact that we cannot use any special name convention (see #181). 

Just to be sure I got the solution, in "top_projects" (that should be singular I guess) you specify the name of the main project that consists of several sources of the same type to be analyzed. Isn't?

**Comment by valeriocos** [comment]
> Just to be sure I got the solution, in "top_projects" (that should be singular I guess) you specify the name of the main project that consists of several sources of the same type to be analyzed. Isn't?

Yes! I guess the sources can be of different types too (but I didn't try). WRT "top_projects" is a list where the given project is included (e.g., `org.eclipse.actf.ai.git` is part of `actf` and `eclipse`). Under the hood, ElasticSearch treats the items in the lists as single attributes, thus you can filter by `actf`, `eclipse` or both.

**Pull request merged**
