### PR TITLE
[dashboards] Review dashboards and remove fake data

### PR DESCRIPTION
**Pull request by valeriocos**
This PR removes the fake data and reviews the dashboards. Below a description of each dashboard is provided:

**Overview dashboard**
It contains the following visualizations/tables (from left to right, top to bottom):

- a table that shows the list of las facts
- a pie chart that shows the projects. It can be used to filter by project.
- a pie chart that shows the top projects. It can be used to filter by top project.
- a table with the last recommendations (they come from the trans.rascal.OO metrics)
- a heat map that allows to compare the projects wrt to attributes of the quality model defined [in prosoul](https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/data/qmodel_crossminer.json)
- a bar chart that shows the evolution of bugs (fixed vs closed/non resolved)
- a bar chart that shows the evolution of commits
- a bar chart that shows the evolution of percentage emotions (anger, joy, sadness, surprise, love) in bugs
- a bar chart that shows the evolution of active and inactive users on bug tracker

Captura de pantalla de 2019-05-23 04-05-05

**Dependencies dashboard**
It similar to this dashboard commited at: https://github.com/crossminer/scava/commit/d73999c9e286c38994672ee8729a771975ff960b, but the dependencies are aggregated using an unique count over their names.
It contains the following visualizations/tables (from left to right, top to bottom):

- a visualization that shows the number of total deps
- a pie chart that shows the deps grouped by project
- a pie chart that shows the deps grouped by top project
- a table that shows the deps grouped by type (e.g., osgi and maven) and project
- a table that shows the deps grouped by type and top project
- a graph that relates projects to dependency names (edges size is based on the number times the dep names appear in the index)
- a bar chart that shows the evolution of project deps
- a table that provides details (name, versions, project and time) of the project deps

Captura de pantalla de 2019-05-23 04-24-10

**Facts dashboard**
It contains the following visualizations/tables (from left to right, top to bottom):

- a table that shows the number of stars per project
- a pie chart that shows the projects. It can be used to filter by project.
- a pie chart that shows the top projects. It can be used to filter by top project.
- a radar visualization to compare projects based on the number of stars
- a table with the list of last facts
- a heat map that allows to compare projects and the facts based on the stars of the latter

Captura de pantalla de 2019-05-23 04-32-46

**Debug dashboard**
It is useful to understand the metrics and their values (min, max, evolution, etc.).
It contains several tables that allows to filter the metric based on their types, project they belong to,
names and ids. 3 visualizations allows to aggregate a target metric using the sum, the max and the average operators. At the bottom, 5 boxes show the avg, median, max, min and sum of the target metric.

Captura de pantalla de 2019-05-23 04-38-09

**Quality model dashboard**
It shows the quality model assessment based on the model available [in prosoul repo](https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/data/qmodel_crossminer.json)

It contains the following visualizations/tables (from left to right, top to bottom):
- a table that ranks the projects based on the sum of their scores, which are the normalized values (0-5) of the metrics based on the threshold defined in the quality model.
- a pie chart that shows the projects. It can be used to filter by project
- a heat map that allows to compare projects based on the qm metric scores
- a bar chart that shows the qm metric scores (useful to focus on one project)
- a heat map that allows to compare projects based on the qm attributes (median of the corresponding metric scores)
- a bar chart that shows the qm attributes (useful to focus on one project)
- a heat map that allows to compare projects based on the qm goals (median of the corresponding metric scores)
- a bar chart that shows the qm goals (useful to focus on one project)

Captura de pantalla de 2019-05-23 04-56-16

**Sentiment dashboard**
It has been recently commited (https://github.com/crossminer/scava/pull/234), just some minor changes have been added (setting some visualizations and dashboard titles). Note that some visualizations are empty in the screenshot because the projects analyzed don't have articles info.

- a pie chart that shows the projects. It can be used to filter by project.
- a pie chart that shows the top projects. It can be used to filter by top project.
- two tables that show the cumulative and the percentages of the comments, but in order to see correctly, you will have to filter by project first, then you will see the cumulative and the percentage of the project filtered.
- two bar charts that show the evolution on time of the cumulative and percentages of the comments for all the projects.
- two tables that show the cumulative and the percentages of the articles, but in order to see correctly, you will have to filter by project first, then you will see the cumulative and the percentage of the project filtered.
- two bar charts that show the evolution on time of the cumulative and percentages of the articles for all the projects.
- a heat map that shows the feeling of the comments that have label for all projects.
- a evolution of the feeling of the comments that have label. In order to see correctly, you will have to filter by project first, then you will see the cumulative and the percentage of the project filtered.

Captura de pantalla de 2019-05-23 04-58-07

**User dashboard**
It is useful to show user activity. It contains the following visualizations/tables (from left to right, top to bottom):

- a pie chart that shows the projects. It can be used to filter by project.
- a pie chart that shows the top projects. It can be used to filter by top project.
- a table that shows the top users based on the sum of their churns
- a table that shows the churn evolution (it can be filtered by user)
- a bar chart that shows the evolution of active and inactive users on bug tracker

Captura de pantalla de 2019-05-23 05-07-35

### CODE REVIEW

**Comment by dlumbrer** [comment]
LGTM @valeriocos , nice panels, good work!!!!!

**Comment by mhow2** [comment]
I think that in the scava-overview, the "Users on issue tracker" should show inactive and active users like in the user dashboard. (instead of "users" and "inactiveusers").

**Comment by mhow2** [comment]
"Dependencies details" is it normal to get several dep with the same name / different version ? To be checked.

**Comment by valeriocos** [comment]
```
"Dependencies details" is it normal to get several dep with the same name / different version ? To be checked.
```

@mhow2 I checked the data and it seems that the API returns a given dependency with and without version info. For instance, for the project `docdokuplm` we have:
- `bundle://maven/args4j/args4j/2.0.23`
- `bundle://maven/args4j/args4j/none`

I modified the last table in the dep dashboard, now only the dependencies with version are shown.

**Comment by mhow2** [comment]
> ```
> "Dependencies details" is it normal to get several dep with the same name / different version ? To be checked.
> ```
> 
> @mhow2 I checked the data and it seems that the API returns a given dependency with and without version info. For instance, for the project `docdokuplm` we have:
> 
>     * `bundle://maven/args4j/args4j/2.0.23`
> 
>     * `bundle://maven/args4j/args4j/none`
> 
> 
> I modified the last table in the dep dashboard, now only the dependencies with version are shown.

I confirm I don't see the deps with `none` version anymore.

**Comment by mhow2** [comment]
Everywhere we have "Max metric_es_value" or similar for the y axis, we should have a self-explanatory label instead.

**Comment by mhow2** [comment]
Now speaking of `scava-sentiment` dashboard : **sentiment** and **emotion** are two different things in the NLP analysis.

- Emotions are of joy, anger... And the said dashboard mention "sentiment" when it shouldn't. (in the title as well as in the viz labels).
- Sentiment is something like `-0.019966159015893936`, ie a flot between -1 and +1. As far as I see we miss a viz/dashboard for it.

You'll find more infos and details in the [metric documentation ](https://scava-docs.readthedocs.io/en/latest/user-guide/metrics/)

**Comment by valeriocos** [comment]
> Everywhere we have "Max metric_es_value" or similar for the y axis, we should have a self-explanatory label instead.

I see that only the following dashboards are the target of your comment:
- scava-overview (fixed with 181fdca9f)
- scava-project (cannot be fixed and it is not needed since this is a dev/debug dashboard and metric_es_value depends on the selected metric)
- scava-sentiment (this requires some rework, see next comment)

**Comment by valeriocos** [comment]
> [Now speaking of scava-sentiment dashboard : sentiment and emotion are two different things in the NLP analysis.
> 
> Emotions are of joy, anger... And the said dashboard mention "sentiment" when it shouldn't. (in the title as well as in the viz labels).
> Sentiment is something like -0.019966159015893936, ie a flot between -1 and +1. As far as I see we miss a viz/dashboard for it.
> You'll find more infos and details in the metric documentation](url)

If you agree, let's merge this PR and rework this dashboard in another PR. We could rename it as `feeling dashboard` and add at least a visualization about sentiment, what do you think ?

**Comment by valeriocos** [comment]
Following the discussion with @mhow2 the qm heat map visualizations have been updated. Now they show 6 levels (from 0 to 5) plus the value of the qm metric/attribute/goal on the corresponding square of the heat map.

Captura de pantalla de 2019-05-29 08-59-27

**Comment by mhow2** [comment]
LGTM thanks !

**Comment by valeriocos** [comment]
Thank you for the review @mhow2

**Pull request merged**
