### PR TITLE
Ehu test merge

### PR DESCRIPTION
**Pull request by creat89**
Hello,

Here are the main changes:

 * Add of GitLab Reader
 * Update of GitHub Reader (needs to add the workflow projects using the import tool as they are not maven)
 * Add of Mantis Reader
 * Add of EclipseForums Reader
 * Update classifiers:
   * Sentiment
   * Emotion
   * Request/Reply
 * Add code detector
 * Add multiple NLP tools
 * Update BitBucket Reader
 * Update Metrics
 * Solve some bugs found in readers and metrics
 * Includes a patch for ProjectAnalyser in ProjectanalyserEHU.java
 * Update Severity classifier loader
 * Update Content classifier loader

### CODE REVIEW

**Comment by creat89** [comment]
I was trying to avoid the first 7 commits from the master branch, but I haven't found the correct way to remove them from my PR. Any ideas?

**Comment by valeriocos** [comment]
why are you sending the pr to the master branch, it shouldn't be the dev one?

anyway, supposing that your fork is in origin and the original repo is in upstream, you could do:
- git checkout - b your-branch master
- create your commits
- git fetch upstream (to get the latest changes in upstream)
- git rebase upstream/master (to sync your branch with the one in upstream)
- git push origin (your pr should appear with just your new commits)

hope this helps (i hope i understood the issue correctly)

**Comment by creat89** [comment]
I'm not sending the PR to the master but to the branch. But, it seems that originally I started to work on the master instead of the dev branch. So I want to remove the first 7 commits that are not mine. I'll try that, thanks Valerio.

**Comment by valeriocos** [comment]
aaa ok, so maybe you can do it:
git rebase -i HEAD~(number of commits to change)

a new editor will appear, just remove the commits you want (in this case the 7 ones from the master branch). it may be possible that you will have to fix some conflicts

**Pull request closed without merging**
